services:
  postgres:
    container_name: postgres-review-my-cv-db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - review-my-cv-network
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-review-my-cv
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  review-my-cv-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local