spring:
  profiles:
    active: dev
springdoc:
  default-produces-media-type: application/json
#server:
#  servlet:
#    context-path: /api/v1
#  port: 8181
debug: true
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.core: ERROR
